const html = `<!DOCTYPE html>
<head>
	<script type="module" src="/js/main.js"></script>
</head>
<body>
  <h1>Hello World</h1>
  <p>This markup was generated by a Service Worker.</p>
</body>`

async function handleRequest(request) {
  return new Response(html, {
    headers: {
      "content-type": "text/html;charset=UTF-8",
    },
  })
}

addEventListener("fetch", event => {
  return event.respondWith(handleRequest(event.request))
})